version: '3.8'

services:
    db:
      image: mysql
      restart: unless-stopped
      environment:
        MYSQL_ROOT_PASSWORD: 12345
      ports:
        - 3306:3306
      volumes:
        - my-db:/var/lib/mysql
    migrations:
      depends_on:
        - db
      build: .
      restart: on-failure
      env_file: ./.env
      environment:
        - DATABASE_URL=$DATABASE_URL
      stdin_open: true
      tty: true
      command: npm run prisma:migrate
    next-app:
      depends_on:
        - db
        - migrations
      container_name: next-app
      build:
        context: .
        dockerfile: Dockerfile
#        args:
#          ENV DATABASE_URL: ${DATABASE_URL}
      restart: always
      ports:
        - 3000:3000

volumes:
  my-db: